Repository Incendo/cloud, pull requests merged in 2023-12, with the labels that each got.

#538 feature(annotations) `@ExceptionHandler` methods
  cloud-annotations/src/main/java/cloud/commandframework/annotations/AnnotationParser.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/exception/ExceptionHandler.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/exception/ExceptionHandlerFactory.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/exception/MethodExceptionHandler.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/exception/package-info.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/exception/MethodExceptionHandlerTest.java
  cloud-core/src/main/java/cloud/commandframework/annotations/injection/ParameterInjector.java
Labels: 2.0.0

#548 chore: clean up CommandMeta
  cloud-annotations/src/main/java/cloud/commandframework/annotations/AnnotationParser.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/AnnotationParserTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/TestCommandManager.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/ArgumentDrivenCommandsTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/MethodSuggestionProviderTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/RepeatableCommandMethodTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/RepeatableFlagTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/RequiredSenderDeductionTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/StringProcessingTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/issue/Issue262.java
  cloud-core/src/main/java/cloud/commandframework/Command.java
  cloud-core/src/main/java/cloud/commandframework/CommandBean.java
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/extra/confirmation/CommandConfirmationManager.java
  cloud-core/src/main/java/cloud/commandframework/meta/CommandMeta.java
  cloud-core/src/main/java/cloud/commandframework/meta/CommandMetaBuilder.java
  cloud-core/src/main/java/cloud/commandframework/meta/SimpleCommandMeta.java
  cloud-core/src/main/java/cloud/commandframework/meta/SimpleKey.java
  cloud-core/src/test/java/cloud/commandframework/CommandBeanTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandDeletionTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandManagerTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandPermissionTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandPreProcessorTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandTreeTest.java
  cloud-core/src/test/java/cloud/commandframework/execution/CommandExecutionCoordinatorTest.java
  cloud-core/src/test/java/cloud/commandframework/issue/Issue281.java
  cloud-core/src/test/java/cloud/commandframework/util/TestUtils.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/JavacordCommandManager.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandManager.java
  cloud-irc/cloud-pircbotx/src/main/java/cloud/commandframework/pircbotx/PircBotXCommandManager.java
  cloud-kotlin/cloud-kotlin-coroutines-annotations/src/test/kotlin/cloud/commandframework/kotlin/coroutines/annotations/KotlinAnnotatedMethodsTest.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/test/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingHandlerTest.kt
  cloud-kotlin/cloud-kotlin-extensions/src/main/kotlin/cloud/commandframework/kotlin/MutableCommandBuilder.kt
  cloud-kotlin/cloud-kotlin-extensions/src/test/kotlin/cloud/commandframework/kotlin/CommandBuildingDSLTest.kt
  cloud-minecraft/cloud-brigadier/src/test/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactoryTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandMeta.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/BungeeCommandManager.java
  cloud-minecraft/cloud-cloudburst/src/main/java/cloud/commandframework/cloudburst/CloudburstCommandManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricServerCommandManager.java
  cloud-minecraft/cloud-sponge7/src/main/java/cloud/commandframework/sponge7/SpongeCommandManager.java
  cloud-minecraft/cloud-sponge7/src/main/java/cloud/commandframework/sponge7/SpongeMetaKeys.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityCommandManager.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/feature/ProcessorExample.java
Labels: 2.0.0

#549 chore: clean up CloudKey
  cloud-annotations/src/main/java/cloud/commandframework/annotations/MethodCommandExecutionHandler.java
  cloud-core/src/main/java/cloud/commandframework/Command.java
  cloud-core/src/main/java/cloud/commandframework/CommandComponent.java
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/TypedCommandComponent.java
  cloud-core/src/main/java/cloud/commandframework/arguments/CommandArgument.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandContextImpl.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandContext.java
  cloud-core/src/main/java/cloud/commandframework/extra/confirmation/CommandConfirmationManager.java
  cloud-core/src/main/java/cloud/commandframework/keys/CloudKey.java
  cloud-core/src/main/java/cloud/commandframework/keys/CloudKeyContainer.java
  cloud-core/src/main/java/cloud/commandframework/keys/CloudKeyHolder.java
  cloud-core/src/main/java/cloud/commandframework/keys/SimpleCloudKey.java
  cloud-core/src/main/java/cloud/commandframework/meta/CommandMeta.java
  cloud-core/src/main/java/cloud/commandframework/meta/CommandMetaBuilder.java
  cloud-core/src/main/java/cloud/commandframework/meta/SimpleCommandMeta.java
  cloud-core/src/main/java/cloud/commandframework/permission/PredicatePermission.java
  cloud-core/src/main/java/cloud/commandframework/permission/WrappingPredicatePermission.java
  cloud-core/src/test/java/cloud/commandframework/CommandBeanTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandPermissionTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandPreProcessorTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandTreeTest.java
  cloud-core/src/test/java/cloud/commandframework/feature/DefaultValueTest.java
  cloud-core/src/test/java/cloud/commandframework/keys/CloudKeyContainerTest.java
  cloud-kotlin/cloud-kotlin-extensions/src/main/kotlin/cloud/commandframework/kotlin/extension/CloudKeyExtensions.kt
  cloud-kotlin/cloud-kotlin-extensions/src/test/kotlin/cloud/commandframework/kotlin/CommandBuildingDSLTest.kt
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommand.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandContextKeys.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandMeta.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/BungeeContextKeys.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandContextKeys.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricServerCommandManager.java
  cloud-minecraft/cloud-fabric/src/testmod/java/cloud/commandframework/fabric/testmod/FabricExample.java
  cloud-minecraft/cloud-sponge7/src/main/java/cloud/commandframework/sponge7/CloudCommandCallable.java
  cloud-minecraft/cloud-sponge7/src/main/java/cloud/commandframework/sponge7/SpongeMetaKeys.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityContextKeys.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/BuilderModifierExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/CommandBeanExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/CompoundArgumentExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/feature/ProcessorExample.java
Labels: 2.0.0

#547 feat: make immutables generate apiguardian annotations
  build-logic/src/main/kotlin/cloud.base-conventions.gradle.kts
  cloud-core/src/main/java/cloud/commandframework/internal/ImmutableBuilder.java
  cloud-core/src/main/java/cloud/commandframework/internal/ImmutableImpl.java
  gradle/libs.versions.toml
Labels: 2.0.0

#552 feat(annotations): add `@Default`
  cloud-annotations/src/main/java/cloud/commandframework/annotations/Argument.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/ArgumentExtractorImpl.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/Default.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/AnnotationParserTest.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/StringArrayExample.java
Labels: 2.0.0

#551 feat(annotations): annotation-less arguments, and description mappers
  README.md
  cloud-annotations/src/main/java/cloud/commandframework/annotations/AnnotationParser.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/Argument.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/ArgumentExtractorImpl.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/DescriptionMapper.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/FlagExtractorImpl.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/ParameterNameExtractor.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/StandardArgumentExtractor.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/processing/CommandMethodVisitor.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/ArgumentWithoutAnnotationTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/DescriptionMapperTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/processing/CommandMethodProcessorTest.java
  cloud-annotations/src/test/resources/TestCommandMethodWithoutArgumentAnnotations.java
Labels: 2.0.0

#543 feature: new help system
  cloud-annotations/src/test/java/cloud/commandframework/annotations/issue/Issue262.java
  cloud-core/src/main/java/cloud/commandframework/CommandHelpHandler.java
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/help/CommandPredicate.java
  cloud-core/src/main/java/cloud/commandframework/help/HelpHandler.java
  cloud-core/src/main/java/cloud/commandframework/help/HelpHandlerFactory.java
  cloud-core/src/main/java/cloud/commandframework/help/HelpQuery.java
  cloud-core/src/main/java/cloud/commandframework/help/HelpRenderer.java
  cloud-core/src/main/java/cloud/commandframework/help/StandardHelpHandler.java
  cloud-core/src/main/java/cloud/commandframework/help/StandardHelpHandlerFactory.java
  cloud-core/src/main/java/cloud/commandframework/help/package-info.java
  cloud-core/src/main/java/cloud/commandframework/help/result/CommandEntry.java
  cloud-core/src/main/java/cloud/commandframework/help/result/HelpQueryResult.java
  cloud-core/src/main/java/cloud/commandframework/help/result/IndexCommandResult.java
  cloud-core/src/main/java/cloud/commandframework/help/result/MultipleCommandResult.java
  cloud-core/src/main/java/cloud/commandframework/help/result/VerboseCommandResult.java
  cloud-core/src/main/java/cloud/commandframework/help/result/package-info.java
  cloud-core/src/test/java/cloud/commandframework/CommandHelpHandlerTest.java
  cloud-core/src/test/java/cloud/commandframework/help/StandardHelpHandlerTest.java
  cloud-kotlin/cloud-kotlin-extensions/src/test/kotlin/cloud/commandframework/kotlin/CommandBuildingDSLTest.kt
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/MinecraftHelp.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/HelpExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/HelpExample.java
Labels: 2.0.0

#550 chore: clean up captions
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/arguments/preprocessor/RegexPreprocessor.java
  cloud-core/src/main/java/cloud/commandframework/captions/Caption.java
  cloud-core/src/main/java/cloud/commandframework/captions/CaptionFormatter.java
  cloud-core/src/main/java/cloud/commandframework/captions/CaptionProvider.java
  cloud-core/src/main/java/cloud/commandframework/captions/CaptionRegistry.java
  cloud-core/src/main/java/cloud/commandframework/captions/CaptionVariable.java
  cloud-core/src/main/java/cloud/commandframework/captions/ConstantCaptionProvider.java
  cloud-core/src/main/java/cloud/commandframework/captions/SimpleCaptionRegistry.java
  cloud-core/src/main/java/cloud/commandframework/captions/SimpleCaptionRegistryFactory.java
  cloud-core/src/main/java/cloud/commandframework/captions/StandardCaptionKeys.java
  cloud-core/src/main/java/cloud/commandframework/captions/StandardCaptionRegistry.java
  cloud-core/src/main/java/cloud/commandframework/captions/StandardCaptionRegistryFactory.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandContext.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/parsing/ParserException.java
  cloud-core/src/test/java/cloud/commandframework/caption/PlaceholderReplacingCaptionFormatterTest.java
  cloud-core/src/test/java/cloud/commandframework/caption/StandardCaptionRegistryTest.java
  cloud-irc/cloud-pircbotx/src/main/java/cloud/commandframework/pircbotx/PircBotXCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCaptionKeys.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCaptionRegistry.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/BungeeCaptionKeys.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/BungeeCommandManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCaptionKeys.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCaptionRegistry.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/ComponentCaptionFormatter.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityCaptionKeys.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityCommandManager.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/RegexExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/RegexExample.java
Labels: 2.0.0

#556 chore(core): clean up `CommandContext`
  cloud-annotations/src/main/java/cloud/commandframework/annotations/MethodCommandExecutionHandler.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/exception/MethodExceptionHandler.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/exception/MethodExceptionHandlerTest.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandContext.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandContextImpl.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/compound/CompoundParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandContext.java
  cloud-core/src/main/java/cloud/commandframework/extra/confirmation/CommandConfirmationManager.java
  cloud-core/src/main/java/cloud/commandframework/keys/MutableCloudKeyContainer.java
  cloud-core/src/test/java/cloud/commandframework/CommandManagerTest.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandPreprocessor.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/CloudBrigadierManager.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/WrappedBrigadierParser.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/suggestion/BrigadierSuggestionFactory.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandPreprocessor.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/ItemStackPredicateParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandPreprocessor.java
  cloud-minecraft/cloud-fabric/src/testmod/java/cloud/commandframework/fabric/testmod/FabricClientExample.java
  cloud-minecraft/cloud-fabric/src/testmod/java/cloud/commandframework/fabric/testmod/FabricExample.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/MinecraftExceptionHandler.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/ConfirmationExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/HelpExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/AggregateCommandExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/CommandBeanExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/CompoundArgumentExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/ConfirmationExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/EnumExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/FlagExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/HelpExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/RegexExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/StringArrayExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/TaskRecipeExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/minecraft/BlockPredicateExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/minecraft/ItemStackExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/minecraft/ItemStackPredicateExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/minecraft/NamespacedKeyExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/minecraft/SelectorExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/feature/ProcessorExample.java
  examples/example-bungee/src/main/java/cloud/commandframework/examples/bungee/ExamplePlugin.java
  examples/example-jda/src/main/java/cloud/commandframework/examples/jda/ExampleBot.java
  examples/example-velocity/src/main/java/cloud/commandframework/examples/velocity/ExampleVelocityPlugin.java
Labels: 2.0.0

#558 chore(core): delete CommandArgument
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/arguments/CommandArgument.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/package-info.java
  cloud-kotlin/cloud-kotlin-extensions/src/main/kotlin/cloud/commandframework/kotlin/MutableCommandBuilder.kt
Labels: 2.0.0

#555 chore(minecraft-extras): make MinecraftHelp immutable
  cloud-core/src/main/java/cloud/commandframework/internal/StagedImmutableBuilder.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/MinecraftHelp.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/ExamplePlugin.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/HelpExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/minecraft/TextColorExample.java
Labels: minecraft, 2.0.0

#561 fix(core): accept parsers for supertypes of C
  cloud-core/src/main/java/cloud/commandframework/Command.java
  cloud-core/src/main/java/cloud/commandframework/CommandComponent.java
  cloud-core/src/test/java/cloud/commandframework/feature/ChangedCommandSenderTypeTest.java
Labels: 2.0.0

#562 feat(kotlin): add SuspendingArgumentParser/SuggestionProvider
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParser.java
  cloud-kotlin/cloud-kotlin-coroutines/src/main/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingArgumentParser.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/main/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingSuggestionProvider.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/test/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingArgumentParserTest.kt
Labels: 2.0.0

#514 chore(deps): update dependencies
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/cloud.base-conventions.gradle.kts
  build-logic/src/main/kotlin/cloud.kotlin-conventions.gradle.kts
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/EnumParser.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandInput.java
  cloud-core/src/main/java/cloud/commandframework/internal/CommandInputTokenizer.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/ArgumentTestHelper.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/JavacordCommand.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitPluginRegistrationHandler.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/MaterialParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/LocationCoordinate.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SelectorUtils.java
  cloud-minecraft/cloud-bukkit/src/test/java/cloud/commandframework/bukkit/argument/MaterialArgumentTest.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/MinecraftExceptionHandler.java
  cloud-minecraft/cloud-minecraft-extras/src/test/java/cloud/commandframework/minecraft/extras/TextColorArgumentTest.java
  cloud-services/src/main/java/cloud/commandframework/services/ServiceRepository.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/FlagExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/FlagExample.java
  examples/example-jda/src/main/java/cloud/commandframework/examples/jda/PermissionRegistry.java
  examples/example-velocity/src/main/java/cloud/commandframework/examples/velocity/ExampleVelocityPlugin.java
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: 2.0.0

#564 Update MinecraftExceptionHandler to better use new exception handling API
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/MinecraftExceptionHandler.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/ExamplePlugin.java
  examples/example-bungee/src/main/java/cloud/commandframework/examples/bungee/ExamplePlugin.java
  examples/example-velocity/src/main/java/cloud/commandframework/examples/velocity/ExampleVelocityPlugin.java
Labels: enhancement, minecraft, 2.0.0

#571 Remove ArgumentParser#isContextFree
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/MappedArgumentParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/BooleanParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ByteParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/CharacterParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/DoubleParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/EnumParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/FloatParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/IntegerParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/LongParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ShortParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/StringParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/UUIDParser.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/WrappedBrigadierParser.java
Labels: 2.0.0

#563 chore(core): extract state handling
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/state/RegistrationState.java
  cloud-core/src/main/java/cloud/commandframework/state/State.java
  cloud-core/src/main/java/cloud/commandframework/state/Stateful.java
  cloud-core/src/main/java/cloud/commandframework/state/package-info.java
  cloud-core/src/test/java/cloud/commandframework/CommandRegistrationStateTest.java
  cloud-core/src/test/java/cloud/commandframework/state/StatefulTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-cloudburst/src/main/java/cloud/commandframework/cloudburst/CloudburstCommandManager.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperCommandManager.java
Labels: 2.0.0

#568 Refactor selector data types and exceptions
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCaptionKeys.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCaptionRegistry.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/arguments/selector/EntitySelector.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/arguments/selector/MultiplePlayerSelector.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/arguments/selector/package-info.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/data/MultipleEntitySelector.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/data/MultiplePlayerSelector.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/data/Selector.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/data/SingleEntitySelector.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/data/SinglePlayerSelector.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/MultipleEntitySelectorParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/MultiplePlayerSelectorParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SelectorParseException.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SelectorUnsupportedException.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SelectorUtils.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SingleEntitySelectorParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SinglePlayerSelectorParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/FabricVanillaArgumentParsers.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/data/Selector.java
  cloud-minecraft/cloud-fabric/src/testmod/java/cloud/commandframework/fabric/testmod/FabricExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/minecraft/SelectorExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/minecraft/SelectorExample.java
Labels: minecraft, 2.0.0

#567 Clean up SuggestionProvider hierarchy
  build-logic/src/main/kotlin/cloud.base-conventions.gradle.kts
  cloud-annotations/src/main/java/cloud/commandframework/annotations/AnnotationParser.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/ArgumentAssemblerImpl.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/parsers/MethodArgumentParser.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/suggestions/MethodSuggestionProvider.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/AnnotationParserTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/MethodSuggestionProviderTest.java
  cloud-core/src/main/java/cloud/commandframework/CommandComponent.java
  cloud-core/src/main/java/cloud/commandframework/arguments/LiteralParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/MappedArgumentParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/BooleanParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ByteParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/DurationParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/EnumParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/IntegerParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/LongParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ShortParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/BlockingSuggestionProvider.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/SuggestionProvider.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/SuggestionProviderHolder.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandInput.java
  cloud-core/src/test/java/cloud/commandframework/CommandSuggestionsTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/aggregate/AggregateCommandParserTest.java
  cloud-core/src/test/java/cloud/commandframework/execution/CommandExecutionCoordinatorTest.java
  cloud-core/src/test/java/cloud/commandframework/feature/ChangedCommandSenderTypeTest.java
  cloud-kotlin/cloud-kotlin-coroutines-annotations/src/main/kotlin/cloud/commandframework/kotlin/coroutines/annotations/KotlinAnnotatedMethods.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/main/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingSuggestionProvider.kt
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/WrappedBrigadierParser.java
  cloud-minecraft/cloud-brigadier/src/test/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactoryTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/BlockPredicateParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/EnchantmentParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/ItemStackParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/ItemStackPredicateParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/MaterialParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/NamespacedKeyParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/OfflinePlayerParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/PlayerParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/WorldParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/Location2DParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/LocationParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SelectorUtils.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/arguments/PlayerParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/RegistryEntryParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/TeamParser.java
  cloud-minecraft/cloud-fabric/src/testmod/java/cloud/commandframework/fabric/testmod/FabricExample.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/TextColorParser.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/parser/KeyedWorldParser.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/arguments/PlayerParser.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/arguments/ServerParser.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/AggregateCommandExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/HelpExample.java
Labels: 2.0.0

#572 feat: make suggestion processors act on individual suggestions
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/DelegatingSuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/execution/CommandSuggestionProcessor.java
  cloud-core/src/main/java/cloud/commandframework/execution/FilteringCommandSuggestionProcessor.java
  cloud-core/src/main/java/cloud/commandframework/internal/SuggestionContext.java
  cloud-core/src/test/java/cloud/commandframework/execution/CommandSuggestionProcessorTest.java
Labels: 2.0.0

#566 Preserve suggestion tooltips from WrappedBrigadierParsers, and don't join the Brig suggestions future
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/WrappedBrigadierParser.java
Labels: enhancement, minecraft, 2.0.0

#574 Use stylecheck to enforce type use annotation position
  .checkstyle/checkstyle.xml
  build-logic/src/main/kotlin/cloud.base-conventions.gradle.kts
  cloud-annotations/src/main/java/cloud/commandframework/annotations/ArgumentAssemblerImpl.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/FlagAssemblerImpl.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/PatternReplacingStringProcessor.java
  cloud-core/src/main/java/cloud/commandframework/CommandBean.java
  cloud-core/src/main/java/cloud/commandframework/CommandComponent.java
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/annotations/MultiDelegateAnnotationAccessor.java
  cloud-core/src/main/java/cloud/commandframework/arguments/DefaultValue.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParseResult.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/DelegatingSuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/MappingSuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/SimpleSuggestion.java
  cloud-core/src/main/java/cloud/commandframework/captions/CaptionRegistry.java
  cloud-core/src/main/java/cloud/commandframework/captions/StandardCaptionRegistry.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/handling/ExceptionController.java
  cloud-core/src/main/java/cloud/commandframework/execution/AsynchronousCommandExecutionCoordinator.java
  cloud-core/src/main/java/cloud/commandframework/execution/CommandExecutionHandler.java
  cloud-core/src/main/java/cloud/commandframework/help/StandardHelpHandlerFactory.java
  cloud-core/src/main/java/cloud/commandframework/meta/CommandMetaBuilder.java
  cloud-core/src/main/java/cloud/commandframework/meta/SimpleCommandMeta.java
  cloud-core/src/test/java/cloud/commandframework/execution/CommandExecutionCoordinatorTest.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/sender/JavacordCommandSender.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/sender/JavacordPrivateSender.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/sender/JavacordServerSender.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/BrigadierMapping.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/BrigadierMappingBuilder.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/BrigadierMappingsImpl.java
  cloud-minecraft/cloud-brigadier/src/test/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactoryTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitSynchronizer.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/BlockPredicateParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/ItemStackParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/ItemStackPredicateParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandPreprocessor.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandRegistrationHandler.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricExceptionHandler.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/RegistryEntryParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/SidedArgumentParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/TeamParser.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/MinecraftExceptionHandler.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/NativeAudienceProvider.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/parser/KeyedWorldParser.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/suggestions/BrigadierAsyncCommandSuggestionListener.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/suggestions/tooltips/NativeCompletionMapper.java
  cloud-services/src/main/java/cloud/commandframework/services/ServiceFilterHandler.java
  cloud-services/src/main/java/cloud/commandframework/services/ServicePipeline.java
  cloud-services/src/main/java/cloud/commandframework/services/ServiceRepository.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/FlagExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/minecraft/LocationExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/minecraft/NamespacedKeyExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/AggregateCommandExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/CommandBeanExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/PermissionExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/TaskRecipeExample.java
  gradle/libs.versions.toml
Labels: 2.0.0

#575 Remove cloud-tasks
  cloud-minecraft/cloud-bukkit/build.gradle.kts
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitSynchronizer.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperCommandManager.java
  cloud-tasks/build.gradle.kts
  cloud-tasks/src/main/java/cloud/commandframework/tasks/TaskConsumer.java
  cloud-tasks/src/main/java/cloud/commandframework/tasks/TaskFactory.java
  cloud-tasks/src/main/java/cloud/commandframework/tasks/TaskFunction.java
  cloud-tasks/src/main/java/cloud/commandframework/tasks/TaskRecipe.java
  cloud-tasks/src/main/java/cloud/commandframework/tasks/TaskRecipeStep.java
  cloud-tasks/src/main/java/cloud/commandframework/tasks/TaskRunnable.java
  cloud-tasks/src/main/java/cloud/commandframework/tasks/TaskSynchronizer.java
  cloud-tasks/src/main/java/cloud/commandframework/tasks/package-info.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/AnnotationParserExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/TaskRecipeExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/BuilderExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/TaskRecipeExample.java
  settings.gradle.kts
Labels: 2.0.0

#570 chore: `List<Suggestion>` -> `Iterable<Suggestion>`
  cloud-annotations/src/main/java/cloud/commandframework/annotations/suggestions/MethodSuggestionProvider.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/AnnotationParserTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/MethodSuggestionProviderTest.java
  cloud-core/src/main/java/cloud/commandframework/arguments/LiteralParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/BooleanParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ByteParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/DurationParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/EnumParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/IntegerParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/LongParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ShortParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/BlockingSuggestionProvider.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/SuggestionProvider.java
  cloud-core/src/main/java/cloud/commandframework/internal/SuggestionContext.java
  cloud-core/src/test/java/cloud/commandframework/CommandSuggestionsTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/aggregate/AggregateCommandParserTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/BooleanParserTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/ByteParserTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/EnumParserTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/IntegerParserTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/LongParserTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/ShortParserTest.java
  cloud-kotlin/cloud-kotlin-coroutines-annotations/src/main/kotlin/cloud/commandframework/kotlin/coroutines/annotations/KotlinAnnotatedMethods.kt
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/WrappedBrigadierParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/EnchantmentParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/ItemStackParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/MaterialParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/NamespacedKeyParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/OfflinePlayerParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/PlayerParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/WorldParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/Location2DParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/LocationParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SelectorUtils.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/arguments/PlayerParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/RegistryEntryParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/TeamParser.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/TextColorParser.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/parser/KeyedWorldParser.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/arguments/PlayerParser.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/arguments/ServerParser.java
Labels: 2.0.0

#573 chore(core): update CommandComponent documentation
  cloud-core/src/main/java/cloud/commandframework/CommandComponent.java
Labels: 2.0.0

#576 chore(core): extract settings from `CommandManager`
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/DelegatingSuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/setting/Configurable.java
  cloud-core/src/main/java/cloud/commandframework/setting/EnumConfigurable.java
  cloud-core/src/main/java/cloud/commandframework/setting/ManagerSetting.java
  cloud-core/src/main/java/cloud/commandframework/setting/Setting.java
  cloud-core/src/main/java/cloud/commandframework/setting/package-info.java
  cloud-core/src/test/java/cloud/commandframework/CommandRegistrationStateTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandSuggestionsTest.java
  cloud-core/src/test/java/cloud/commandframework/ParserRegistryTest.java
  cloud-core/src/test/java/cloud/commandframework/feature/ArbitraryPositionFlagTest.java
  cloud-core/src/test/java/cloud/commandframework/settings/EnumConfigurableTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitPluginRegistrationHandler.java
Labels: 2.0.0

#579 chore(core): remove `tokenize` from `CommandInput`
  cloud-annotations/src/main/java/cloud/commandframework/annotations/AnnotationParser.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/StringArrayParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/StringParser.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandInput.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/StringArrayParserTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/StringParserTest.java
  cloud-core/src/test/java/cloud/commandframework/context/CommandInputTest.java
Labels: 2.0.0

#578 chore: `Permission` refactoring
  cloud-annotations/src/main/java/cloud/commandframework/annotations/BuilderDecorator.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/FlagAssemblerImpl.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/FlagDescriptor.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/StringProcessingTest.java
  cloud-core/src/main/java/cloud/commandframework/Command.java
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlag.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandContext.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/NoPermissionException.java
  cloud-core/src/main/java/cloud/commandframework/permission/AndPermission.java
  cloud-core/src/main/java/cloud/commandframework/permission/CommandPermission.java
  cloud-core/src/main/java/cloud/commandframework/permission/OrPermission.java
  cloud-core/src/main/java/cloud/commandframework/permission/Permission.java
  cloud-core/src/main/java/cloud/commandframework/permission/PredicatePermission.java
  cloud-core/src/test/java/cloud/commandframework/CommandPermissionTest.java
  cloud-core/src/test/java/cloud/commandframework/PermissionTest.java
  cloud-kotlin/cloud-kotlin-extensions/src/main/kotlin/cloud/commandframework/kotlin/MutableCommandBuilder.kt
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/permission/BrigadierPermissionChecker.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/permission/BrigadierPermissionPredicate.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommand.java
Labels: 2.0.0

#580 chore: refactor injection services
  cloud-annotations/src/main/java/cloud/commandframework/annotations/MethodCommandExecutionHandler.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/ParameterInjectionTest.java
  cloud-core/src/main/java/cloud/commandframework/annotations/injection/GuiceInjectionService.java
  cloud-core/src/main/java/cloud/commandframework/annotations/injection/InjectionRequest.java
  cloud-core/src/main/java/cloud/commandframework/annotations/injection/InjectionService.java
  cloud-core/src/main/java/cloud/commandframework/annotations/injection/ParameterInjector.java
  cloud-core/src/main/java/cloud/commandframework/annotations/injection/ParameterInjectorRegistry.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandContext.java
  cloud-core/src/test/java/cloud/commandframework/ParameterInjectorRegistryTest.java
Labels: 2.0.0

#581 feat(core): extract command execution from CommandManager
  cloud-annotations/src/test/java/cloud/commandframework/annotations/AnnotationParserTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/exception/MethodExceptionHandlerTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/ArgumentDrivenCommandsTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/ArgumentWithoutAnnotationTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/RepeatableCommandMethodTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/RepeatableFlagTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/RequiredSenderDeductionTest.java
  cloud-core/src/main/java/cloud/commandframework/CommandExecutor.java
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/StandardCommandExecutor.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/DelegatingSuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/SuggestionFactory.java
  cloud-core/src/test/java/cloud/commandframework/CommandDeletionTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandManagerTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandPerformanceTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandPostProcessorTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandPreProcessorTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandTreeTest.java
  cloud-core/src/test/java/cloud/commandframework/ExecutionBenchmark.java
  cloud-core/src/test/java/cloud/commandframework/PermissionTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/DurationParserTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/StringArgumentTest.java
  cloud-core/src/test/java/cloud/commandframework/context/ParsingContextTest.java
  cloud-core/src/test/java/cloud/commandframework/execution/CommandExecutionCoordinatorTest.java
  cloud-core/src/test/java/cloud/commandframework/feature/ArbitraryPositionFlagTest.java
  cloud-core/src/test/java/cloud/commandframework/feature/ChangedCommandSenderTypeTest.java
  cloud-core/src/test/java/cloud/commandframework/feature/DefaultValueTest.java
  cloud-core/src/test/java/cloud/commandframework/feature/RepeatableFlagTest.java
  cloud-core/src/test/java/cloud/commandframework/issue/Issue281.java
  cloud-core/src/test/java/cloud/commandframework/issue/Issue321.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/JavacordCommand.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandListener.java
  cloud-irc/cloud-pircbotx/src/main/java/cloud/commandframework/pircbotx/CloudListenerAdapter.java
  cloud-kotlin/cloud-kotlin-coroutines-annotations/src/main/kotlin/cloud/commandframework/kotlin/coroutines/annotations/KotlinAnnotatedMethods.kt
  cloud-kotlin/cloud-kotlin-coroutines-annotations/src/test/kotlin/cloud/commandframework/kotlin/coroutines/annotations/KotlinAnnotatedMethodsTest.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/test/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingArgumentParserTest.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/test/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingHandlerTest.kt
  cloud-kotlin/cloud-kotlin-extensions/src/test/kotlin/cloud/commandframework/kotlin/CommandBuildingDSLTest.kt
  cloud-minecraft/cloud-brigadier/src/test/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactoryTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommand.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/BungeeCommand.java
  cloud-minecraft/cloud-cloudburst/src/main/java/cloud/commandframework/cloudburst/CloudburstCommand.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricExecutor.java
  cloud-minecraft/cloud-sponge7/src/main/java/cloud/commandframework/sponge7/CloudCommandCallable.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityExecutor.java
Labels: 2.0.0

#582 feat(core): extract command builder creation from CommandManager
  cloud-core/src/main/java/cloud/commandframework/CommandBuilderSource.java
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
Labels: 2.0.0

#587 docs: update the readme
  README.md
Labels: 2.0.0

#584 feat: make CF parsers return `ArgumentParseResult`
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateResultMapper.java
  cloud-core/src/main/java/cloud/commandframework/arguments/compound/CompoundParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParseResult.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/MappedArgumentParser.java
  cloud-core/src/test/java/cloud/commandframework/arguments/aggregate/AggregateCommandParserTest.java
  cloud-core/src/test/java/cloud/commandframework/execution/CommandExecutionCoordinatorTest.java
  cloud-core/src/test/java/cloud/commandframework/truth/ArgumentParseResultSubject.java
  cloud-kotlin/cloud-kotlin-coroutines/src/main/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingArgumentParser.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/test/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingArgumentParserTest.kt
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactory.java
  cloud-minecraft/cloud-brigadier/src/test/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactoryTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/BlockPredicateParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/ItemStackParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/ItemStackPredicateParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/MultiplePlayerSelectorParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SelectorUtils.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SinglePlayerSelectorParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/FabricVanillaArgumentParsers.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/SidedArgumentParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/TeamParser.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/AggregateCommandExample.java
Labels: 2.0.0

#589 chore: convert pre/postprocessing consts to immutables
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/execution/postprocessor/AcceptingCommandPostprocessor.java
  cloud-core/src/main/java/cloud/commandframework/execution/postprocessor/CommandPostprocessingContext.java
  cloud-core/src/main/java/cloud/commandframework/execution/preprocessor/AcceptingCommandPreprocessor.java
  cloud-core/src/main/java/cloud/commandframework/execution/preprocessor/CommandPreprocessingContext.java
  cloud-core/src/main/java/cloud/commandframework/extra/confirmation/CommandConfirmationManager.java
  cloud-core/src/main/java/cloud/commandframework/internal/SuggestionContext.java
  cloud-core/src/test/java/cloud/commandframework/CommandPreProcessorTest.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandPreprocessor.java
  cloud-irc/cloud-pircbotx/src/main/java/cloud/commandframework/pircbotx/PircBotXCommandManager.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/CloudBrigadierManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandPreprocessor.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/BungeeCommandPreprocessor.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandPreprocessor.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityCommandPreprocessor.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/ConfirmationExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/ConfirmationExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/feature/ProcessorExample.java
  examples/example-bungee/src/main/java/cloud/commandframework/examples/bungee/ExamplePlugin.java
Labels: 2.0.0

#591 chore: Rename ArgumentParseResult methods
  cloud-annotations/src/test/java/cloud/commandframework/annotations/AnnotationParserTest.java
  cloud-core/src/main/java/cloud/commandframework/CommandComponent.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParseResult.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParser.java
  cloud-core/src/test/java/cloud/commandframework/truth/ArgumentParseResultSubject.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/Location2DParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/LocationParser.java
  cloud-minecraft/cloud-bukkit/src/test/java/cloud/commandframework/bukkit/argument/EnchantmentArgumentTest.java
  cloud-minecraft/cloud-bukkit/src/test/java/cloud/commandframework/bukkit/argument/Location2DArgumentTest.java
  cloud-minecraft/cloud-bukkit/src/test/java/cloud/commandframework/bukkit/argument/LocationArgumentTest.java
  cloud-minecraft/cloud-bukkit/src/test/java/cloud/commandframework/bukkit/argument/MaterialArgumentTest.java
  cloud-minecraft/cloud-bukkit/src/test/java/cloud/commandframework/bukkit/argument/NamespacedKeyArgumentTest.java
  cloud-minecraft/cloud-bukkit/src/test/java/cloud/commandframework/bukkit/argument/OfflinePlayerArgumentTest.java
  cloud-minecraft/cloud-bukkit/src/test/java/cloud/commandframework/bukkit/argument/PlayerArgumentTest.java
  cloud-minecraft/cloud-bukkit/src/test/java/cloud/commandframework/bukkit/argument/WorldArgumentTest.java
  cloud-minecraft/cloud-minecraft-extras/src/test/java/cloud/commandframework/minecraft/extras/TextColorArgumentTest.java
Labels: 2.0.0

#590 bukkit: parse selectors in correct thread context
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandContextKeys.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandPreprocessor.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SelectorUtils.java
  cloud-minecraft/cloud-paper/build.gradle.kts
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperCommandManager.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperCommandPreprocessor.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/minecraft/SelectorExample.java
  gradle/libs.versions.toml
Labels: enhancement, minecraft, bukkit, 2.0.0

#595 Correctly map Brigadier suggestions to cloud
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/WrappedBrigadierParser.java
Labels: bug, minecraft, 2.0.0

#602 feat(brigadier): use cloud number suggestions by default
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/CloudBrigadierManager.java
Labels: minecraft, 2.0.0

#604 feat(brigadier): add missing generic to BrigadierManagerHolder, switc…
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/BrigadierManagerHolder.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/CloudBrigadierManager.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/BrigadierMappings.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/CloudCommodoreManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandManager.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperCommandManager.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityCommandManager.java
Labels: enhancement, 2.0.0

#601 fix(brigadier): don't force executors by default
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/BrigadierSetting.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/CloudBrigadierManager.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/node/BrigadierNodeFactory.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactory.java
  cloud-minecraft/cloud-brigadier/src/test/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactoryTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/CloudCommodoreManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandRegistrationHandler.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityPluginRegistrationHandler.java
Labels: 2.0.0

#603 fix(brigadier): correctly map aggregate parsers
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactory.java
  cloud-minecraft/cloud-brigadier/src/test/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactoryTest.java
Labels: 2.0.0

#599 feat: preserve whitespace when reading from CommandInput
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateSuggestionProvider.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/StringParser.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandInput.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandInputImpl.java
  cloud-core/src/main/java/cloud/commandframework/execution/FilteringCommandSuggestionProcessor.java
  cloud-core/src/test/java/cloud/commandframework/CommandPreProcessorTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandSuggestionsTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/aggregate/AggregateCommandParserTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/StringArrayParserTest.java
  cloud-core/src/test/java/cloud/commandframework/context/CommandInputTest.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/WrappedBrigadierParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/LocationCoordinateParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/LocationParser.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/AggregateCommandExample.java
Labels: 2.0.0

#605 Remove BlockingSuggestionProvider.ConstantStrings
  cloud-core/src/main/java/cloud/commandframework/arguments/LiteralParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/BooleanParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/EnumParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/BlockingSuggestionProvider.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/EnchantmentParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/ItemStackParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/WorldParser.java
Labels: 2.0.0

#607 Remove ArgumentParser#getRequestedArgumentCount
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/MappedArgumentParser.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/argument/WrappedBrigadierParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/Location2DParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/LocationParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SelectorUtils.java
Labels: 2.0.0

#608 Remove NoInputProvidedException, no input being provided would be a bug.
  cloud-core/src/main/java/cloud/commandframework/arguments/LiteralParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/preprocessor/RegexPreprocessor.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/CharacterParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/DurationParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/EnumParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/StringParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/UUIDParser.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/parsing/NoInputProvidedException.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/parsers/ChannelParser.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/parsers/RoleParser.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/parsers/UserParser.java
  cloud-irc/cloud-pircbotx/src/main/java/cloud/commandframework/pircbotx/arguments/UserParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/EnchantmentParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/MaterialParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/OfflinePlayerParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/PlayerParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/WorldParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/Location2DParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/LocationCoordinateParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/LocationParser.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/arguments/PlayerParser.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/arguments/ServerParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/RegistryEntryParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/TeamParser.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/TextColorParser.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/parser/KeyedWorldParser.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/arguments/PlayerParser.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/arguments/ServerParser.java
Labels: 2.0.0

#611 chore(core): Clean up getting current component chain for exceptions in the tree
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
Labels: 2.0.0

#610 feat(brigadier): simplify inner node construction
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactory.java
Labels: 2.0.0

#609 feat(core): Simplify execution coordination API, expand to cover suggestions execution
  cloud-annotations/src/test/java/cloud/commandframework/annotations/TestCommandManager.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/RequiredSenderDeductionTest.java
  cloud-core/src/main/java/cloud/commandframework/CommandExecutor.java
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/StandardCommandExecutor.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/DelegatingSuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/SuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/execution/AsynchronousCommandExecutionCoordinator.java
  cloud-core/src/main/java/cloud/commandframework/execution/CommandExecutionCoordinator.java
  cloud-core/src/main/java/cloud/commandframework/execution/CommandExecutionHandler.java
  cloud-core/src/main/java/cloud/commandframework/execution/ExecutionCoordinator.java
  cloud-core/src/main/java/cloud/commandframework/execution/ExecutionCoordinatorBuilderImpl.java
  cloud-core/src/main/java/cloud/commandframework/execution/ExecutionCoordinatorImpl.java
  cloud-core/src/main/java/cloud/commandframework/util/CompletableFutures.java
  cloud-core/src/test/java/cloud/commandframework/CommandDeletionTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandManagerTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandTreeTest.java
  cloud-core/src/test/java/cloud/commandframework/PermissionTest.java
  cloud-core/src/test/java/cloud/commandframework/execution/ExecutionCoordinatorTest.java
  cloud-core/src/test/java/cloud/commandframework/issue/Issue281.java
  cloud-core/src/test/java/cloud/commandframework/issue/Issue337.java
  cloud-core/src/test/java/cloud/commandframework/util/TestUtils.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/JavacordCommandManager.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDA4CommandManager.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandManager.java
  cloud-irc/cloud-pircbotx/src/main/java/cloud/commandframework/pircbotx/PircBotXCommandManager.java
  cloud-kotlin/cloud-kotlin-coroutines-annotations/src/main/kotlin/cloud/commandframework/kotlin/coroutines/annotations/KotlinAnnotatedMethods.kt
  cloud-kotlin/cloud-kotlin-coroutines-annotations/src/test/kotlin/cloud/commandframework/kotlin/coroutines/annotations/KotlinAnnotatedMethodsTest.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/main/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingArgumentParser.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/main/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingExecutionHandler.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/main/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingSuggestionProvider.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/test/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingArgumentParserTest.kt
  cloud-kotlin/cloud-kotlin-coroutines/src/test/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingHandlerTest.kt
  cloud-kotlin/cloud-kotlin-extensions/src/test/kotlin/cloud/commandframework/kotlin/CommandBuildingDSLTest.kt
  cloud-minecraft/cloud-brigadier/src/test/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactoryTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/BungeeCommandManager.java
  cloud-minecraft/cloud-cloudburst/src/main/java/cloud/commandframework/cloudburst/CloudburstCommandManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricClientCommandManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricServerCommandManager.java
  cloud-minecraft/cloud-fabric/src/testmod/java/cloud/commandframework/fabric/testmod/FabricClientExample.java
  cloud-minecraft/cloud-fabric/src/testmod/java/cloud/commandframework/fabric/testmod/FabricExample.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperCommandManager.java
  cloud-minecraft/cloud-sponge7/src/main/java/cloud/commandframework/sponge7/CloudInjectionModule.java
  cloud-minecraft/cloud-sponge7/src/main/java/cloud/commandframework/sponge7/SpongeCommandManager.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/CloudInjectionModule.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityCommandManager.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/ExamplePlugin.java
  examples/example-bungee/src/main/java/cloud/commandframework/examples/bungee/ExamplePlugin.java
  examples/example-jda/src/main/java/cloud/commandframework/examples/jda/ExampleBot.java
  examples/example-velocity/src/main/java/cloud/commandframework/examples/velocity/ExampleVelocityPlugin.java
Labels: 2.0.0
