Repository Incendo/cloud, pull requests merged in 2024-01, with the labels that each got.

#612 Remove checked exception from creating bukkit/paper command managers
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitPluginRegistrationHandler.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperCommandManager.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/ExamplePlugin.java
Labels: enhancement, minecraft, 2.0.0

#614 We don't support java serialization
  build-logic/src/main/kotlin/cloud.base-conventions.gradle.kts
  cloud-core/src/main/java/cloud/commandframework/CloudCapability.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/StandardParserRegistry.java
  cloud-core/src/main/java/cloud/commandframework/arguments/preprocessor/RegexPreprocessor.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/BooleanParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ByteParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/CharacterParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/DoubleParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/DurationParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/EnumParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/FloatParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/IntegerParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/LongParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ShortParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/StringParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/UUIDParser.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandInput.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/AmbiguousNodeException.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/ArgumentParseException.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/CommandExecutionException.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/CommandParseException.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/InvalidCommandSenderException.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/InvalidSyntaxException.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/NoCommandInLeafException.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/NoPermissionException.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/NoSuchCommandException.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/parsing/NumberParseException.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/parsing/ParserException.java
  cloud-core/src/test/java/cloud/commandframework/issue/Issue281.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/parsers/UserParser.java
  cloud-irc/cloud-pircbotx/src/main/java/cloud/commandframework/pircbotx/arguments/UserParser.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/BrigadierManagerHolder.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/EnchantmentParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/MaterialParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/NamespacedKeyParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/OfflinePlayerParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/PlayerParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/WorldParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/location/LocationParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SelectorUnsupportedException.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/arguments/PlayerParser.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/arguments/ServerParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/RegistryEntryParser.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/TeamParser.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/TextColorParser.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/arguments/PlayerParser.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/arguments/ServerParser.java
  cloud-services/src/main/java/cloud/commandframework/services/PipelineException.java
  cloud-services/src/main/java/cloud/commandframework/services/types/ConsumerService.java
  cloud-services/src/test/java/cloud/commandframework/services/mock/DefaultMockService.java
Labels: 2.0.0

#596 Fix cloud to Brigadier suggestion mapping
  cloud-annotations/src/test/java/cloud/commandframework/annotations/AnnotationParserTest.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/DelegatingSuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/MappingSuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/SuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/Suggestions.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandInput.java
  cloud-core/src/main/java/cloud/commandframework/context/ParsingContext.java
  cloud-core/src/main/java/cloud/commandframework/execution/ExecutionCoordinator.java
  cloud-core/src/main/java/cloud/commandframework/execution/ExecutionCoordinatorImpl.java
  cloud-core/src/main/java/cloud/commandframework/execution/FilteringCommandSuggestionProcessor.java
  cloud-core/src/main/java/cloud/commandframework/util/StringUtils.java
  cloud-core/src/test/java/cloud/commandframework/CommandDeletionTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandSuggestionsTest.java
  cloud-core/src/test/java/cloud/commandframework/CommandTreeTest.java
  cloud-core/src/test/java/cloud/commandframework/PermissionTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/standard/DurationParserSuggestionsTest.java
  cloud-core/src/test/java/cloud/commandframework/context/ParsingContextTest.java
  cloud-core/src/test/java/cloud/commandframework/execution/CommandSuggestionProcessorTest.java
  cloud-core/src/test/java/cloud/commandframework/feature/MultiTokenParserTest.java
  cloud-core/src/test/java/cloud/commandframework/feature/RepeatableFlagTest.java
  cloud-kotlin/cloud-kotlin-coroutines/src/test/kotlin/cloud/commandframework/kotlin/coroutines/SuspendingArgumentParserTest.kt
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/suggestion/BrigadierSuggestionFactory.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommand.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/BungeeCommand.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/BungeeCommandManager.java
  cloud-minecraft/cloud-cloudburst/src/main/java/cloud/commandframework/cloudburst/CloudburstCommandManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandManager.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperBrigadierListener.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperCommandManager.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/suggestions/AsyncCommandSuggestionListener.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/suggestions/BrigadierAsyncCommandSuggestionListener.java
  cloud-minecraft/cloud-sponge7/src/main/java/cloud/commandframework/sponge7/CloudCommandCallable.java
  cloud-minecraft/cloud-sponge7/src/main/java/cloud/commandframework/sponge7/SpongeCommandManager.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityCommandManager.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/ExamplePlugin.java
Labels: bug, minecraft, 2.0.0

#615 Misc cleanup and docs improvements
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitBrigadierMapper.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommand.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandContextKeys.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandPreprocessor.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitPluginRegistrationHandler.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/CloudBukkitListener.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/CloudCommodoreManager.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperBrigadierListener.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperCommandManager.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperCommandPreprocessor.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/ExamplePlugin.java
Labels: documentation, enhancement, 2.0.0

#592 chore(core): make `ParserRegistry` easier to use
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ParserRegistry.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/StandardParserRegistry.java
  cloud-irc/cloud-pircbotx/src/main/java/cloud/commandframework/pircbotx/PircBotXCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/BlockPredicateParser.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/ItemStackPredicateParser.java
  cloud-minecraft/cloud-bungee/src/main/java/cloud/commandframework/bungee/BungeeCommandManager.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityCommandManager.java
Labels: 2.0.0

#620 chore: remove the confirmation system
  cloud-annotations/src/main/java/cloud/commandframework/annotations/AnnotationParser.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/Confirmation.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/StandardParameters.java
  cloud-core/src/main/java/cloud/commandframework/extra/confirmation/CommandConfirmationManager.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/AnnotationParserExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/ConfirmationExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/BuilderExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/builder/feature/ConfirmationExample.java
  examples/example-bungee/src/main/java/cloud/commandframework/examples/bungee/ExamplePlugin.java
Labels: 2.0.0

#617 feat(annotations): use the same parameter matching logic everywhere
  cloud-annotations/src/main/java/cloud/commandframework/annotations/AnnotationParser.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/MethodCommandExecutionHandler.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/exception/ExceptionHandlerFactory.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/exception/MethodExceptionHandler.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/method/AnnotatedMethodHandler.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/method/AnnotatedMethodHandlerInitiationException.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/method/ParameterValue.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/method/package-info.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/parsers/MethodArgumentParser.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/parsers/Parser.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/suggestions/MethodSuggestionProvider.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/suggestions/SuggestionProviderFactory.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/suggestions/Suggestions.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/MethodSuggestionProviderTest.java
  cloud-kotlin/cloud-kotlin-coroutines-annotations/src/main/kotlin/cloud/commandframework/kotlin/coroutines/annotations/KotlinAnnotatedMethods.kt
Labels: 2.0.0

#618 feat(core): wrap exceptions thrown by injection services
  cloud-core/src/main/java/cloud/commandframework/annotations/injection/ParameterInjectorRegistry.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/InjectionException.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/AnnotationParserExample.java
  examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/annotations/feature/InjectionExample.java
Labels: 2.0.0

#616 feat(core): return proper errors for aggregate parsers
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateCommandParser.java
  cloud-core/src/main/java/cloud/commandframework/captions/StandardCaptionKeys.java
  cloud-core/src/main/java/cloud/commandframework/captions/StandardCaptionRegistry.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/parsing/ParserException.java
  cloud-core/src/test/java/cloud/commandframework/arguments/aggregate/AggregateCommandParserTest.java
Labels: 2.0.0

#619 use cloud-build-logic
  build.gradle.kts
  cloud-annotations/build.gradle.kts
  cloud-bom/build.gradle.kts
  cloud-core/build.gradle.kts
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-discord/cloud-javacord/build.gradle.kts
  cloud-discord/cloud-jda/build.gradle.kts
  cloud-irc/cloud-pircbotx/build.gradle.kts
  cloud-kotlin/cloud-kotlin-coroutines-annotations/build.gradle.kts
  cloud-kotlin/cloud-kotlin-coroutines/build.gradle.kts
  cloud-kotlin/cloud-kotlin-extensions/build.gradle.kts
  cloud-kotlin/cloud-kotlin-extensions/src/main/kotlin/cloud/commandframework/kotlin/extension/ParserDescriptorExtensions.kt
  cloud-minecraft/cloud-brigadier/build.gradle.kts
  cloud-minecraft/cloud-bukkit/build.gradle.kts
  cloud-minecraft/cloud-bungee/build.gradle.kts
  cloud-minecraft/cloud-cloudburst/build.gradle.kts
  cloud-minecraft/cloud-fabric/build.gradle.kts
  cloud-minecraft/cloud-minecraft-extras/build.gradle.kts
  cloud-minecraft/cloud-paper/build.gradle.kts
  cloud-minecraft/cloud-sponge7/build.gradle.kts
  cloud-minecraft/cloud-velocity/build.gradle.kts
  cloud-services/build.gradle.kts
  examples/example-bukkit/build.gradle.kts
  examples/example-bungee/build.gradle.kts
  examples/example-javacord/build.gradle
  examples/example-jda/build.gradle.kts
  examples/example-velocity/build.gradle.kts
  gradle/build-logic/build.gradle.kts
  gradle/build-logic/settings.gradle.kts
  gradle/build-logic/src/main/kotlin/CloudBaseConventions.kt
  gradle/build-logic/src/main/kotlin/CloudExampleConventions.kt
  gradle/build-logic/src/main/kotlin/CloudKotlinConventions.kt
  gradle/build-logic/src/main/kotlin/CloudPublishingConventions.kt
  gradle/build-logic/src/main/kotlin/cloud.base-conventions.gradle.kts
  gradle/build-logic/src/main/kotlin/cloud.errorprone-conventions.gradle.kts
  gradle/build-logic/src/main/kotlin/cloud.example-conventions.gradle.kts
  gradle/build-logic/src/main/kotlin/cloud.kotlin-conventions.gradle.kts
  gradle/build-logic/src/main/kotlin/cloud.parent-build-logic.gradle.kts
  gradle/build-logic/src/main/kotlin/cloud.publishing-conventions.gradle.kts
  gradle/build-logic/src/main/kotlin/cloud.spotless-conventions.gradle.kts
  gradle/build-logic/src/main/kotlin/extensions.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 2.0.0

#624 feat(annotations): support gradle incremental compilation
  cloud-annotations/src/main/resources/META-INF/gradle/incremental.annotation.processors
Labels: 2.0.0

#625 Bump cloud-build-logic to enable incremental immutables annotation processing
  gradle/libs.versions.toml
Labels: 2.0.0

#621 Change default suggestion processor to filter using partialTokenMatches
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/arguments/flags/CommandFlagParser.java
  cloud-core/src/main/java/cloud/commandframework/execution/FilteringCommandSuggestionProcessor.java
  cloud-core/src/test/java/cloud/commandframework/CommandSuggestionsTest.java
  cloud-core/src/test/java/cloud/commandframework/execution/FilteringCommandSuggestionProcessorTest.java
Labels: 2.0.0

#600 Make CommandSuggestionProcessors operate on a stream
  cloud-core/src/main/java/cloud/commandframework/execution/ChainedCommandSuggestionProcessor.java
  cloud-core/src/main/java/cloud/commandframework/execution/CommandSuggestionProcessor.java
  cloud-core/src/main/java/cloud/commandframework/execution/FilteringCommandSuggestionProcessor.java
  cloud-core/src/main/java/cloud/commandframework/internal/SuggestionContext.java
  cloud-core/src/test/java/cloud/commandframework/execution/CommandSuggestionProcessorTest.java
Labels: enhancement, 2.0.0

#627 chore(brigadier): Simplify the Brigadier node factory
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/node/BrigadierNodeFactory.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactory.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/permission/BrigadierPermissionChecker.java
  cloud-minecraft/cloud-brigadier/src/test/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactoryTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/CloudCommodoreManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandRegistrationHandler.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperBrigadierListener.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityPluginRegistrationHandler.java
Labels: 2.0.0

#628 Use common Brigadier Command impl for Fabric and Velocity
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/CloudBrigadierCommand.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandRegistrationHandler.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricExecutor.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityPluginRegistrationHandler.java
Labels: minecraft, 2.0.0

#630 Add convenience methods for setting the command description
  cloud-core/src/main/java/cloud/commandframework/Command.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/RichDescription.java
Labels: 2.0.0

#629 Respect sender types & permissions in more places
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/CommandSyntaxFormatter.java
  cloud-core/src/main/java/cloud/commandframework/arguments/StandardCommandSyntaxFormatter.java
  cloud-core/src/main/java/cloud/commandframework/help/StandardHelpHandler.java
  cloud-core/src/main/java/cloud/commandframework/internal/CommandNode.java
  cloud-core/src/test/java/cloud/commandframework/CommandSuggestionsTest.java
  cloud-core/src/test/java/cloud/commandframework/arguments/StandardCommandSyntaxFormatterTest.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/node/BrigadierNodeFactory.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactory.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/permission/BrigadierPermissionChecker.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/permission/BrigadierPermissionPredicate.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommand.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/CloudCommodoreManager.java
  cloud-minecraft/cloud-minecraft-extras/src/main/java/cloud/commandframework/minecraft/extras/MinecraftHelp.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperBrigadierListener.java
  cloud-minecraft/cloud-sponge7/src/main/java/cloud/commandframework/sponge7/CloudCommandCallable.java
Labels: 2.0.0

#633 Clean up suggestion mapping
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/DelegatingSuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/MappingSuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/arguments/suggestion/SuggestionFactory.java
  cloud-core/src/main/java/cloud/commandframework/execution/ExecutionCoordinator.java
  cloud-core/src/main/java/cloud/commandframework/execution/ExecutionCoordinatorImpl.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/CloudBrigadierManager.java
  cloud-minecraft/cloud-brigadier/src/test/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactoryTest.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommandManager.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/CloudCommodoreManager.java
  cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricCommandManager.java
  cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperBrigadierListener.java
  cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityPluginRegistrationHandler.java
Labels: 2.0.0

#635 chore: remove "hidden" functionality
  cloud-annotations/src/main/java/cloud/commandframework/annotations/AnnotationParser.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/Hidden.java
  cloud-annotations/src/main/java/cloud/commandframework/annotations/ProxiedBy.java
  cloud-core/src/main/java/cloud/commandframework/Command.java
  cloud-core/src/main/java/cloud/commandframework/meta/CommandMeta.java
  cloud-kotlin/cloud-kotlin-extensions/src/main/kotlin/cloud/commandframework/kotlin/MutableCommandBuilder.kt
Labels: 2.0.0

#634 feat(core): make `CommandComponent` immutable
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/BuilderDecoratorTest.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/DescriptionMapperTest.java
  cloud-core/src/main/java/cloud/commandframework/Command.java
  cloud-core/src/main/java/cloud/commandframework/CommandComponent.java
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/TypedCommandComponent.java
  cloud-core/src/main/java/cloud/commandframework/help/StandardHelpHandler.java
  cloud-core/src/main/java/cloud/commandframework/internal/CommandNode.java
  cloud-core/src/test/java/cloud/commandframework/CommandBeanTest.java
  cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/node/LiteralBrigadierNodeFactory.java
  cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommand.java
Labels: 2.0.0

#636 feat(core): copy sender type requirement when proxying commands
  cloud-core/src/main/java/cloud/commandframework/Command.java
Labels: enhancement, 2.0.0

#637 Allow using `@SuppressWarnings("checkstyle:CheckName")` to suppress checkstyle warnings
  .checkstyle/checkstyle.xml
Labels: 2.0.0

#639 Remove Discord modules, they live in the cloud-discord repo now.
  cloud-discord/cloud-javacord/build.gradle.kts
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/JavacordCommand.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/JavacordCommandManager.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/JavacordRegistrationHandler.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/package-info.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/sender/JavacordCommandSender.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/sender/JavacordPrivateSender.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/sender/JavacordServerSender.java
  cloud-discord/cloud-javacord/src/main/java/cloud/commandframework/javacord/sender/package-info.java
  cloud-discord/cloud-jda/build.gradle.kts
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDA4CommandManager.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandListener.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandManager.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandPreprocessor.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandSender.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDAGuildSender.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDAPrivateSender.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/package-info.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/parsers/ChannelParser.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/parsers/RoleParser.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/parsers/UserParser.java
  cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/parsers/package-info.java
  examples/example-javacord/build.gradle
  examples/example-javacord/src/main/java/cloud/commandframework/examples/javacord/ExampleBot.java
  examples/example-javacord/src/main/java/cloud/commandframework/examples/javacord/application/ExampleApplication.java
  examples/example-javacord/src/main/java/cloud/commandframework/examples/javacord/application/package-info.java
  examples/example-javacord/src/main/java/cloud/commandframework/examples/javacord/components/CommandsComponent.java
  examples/example-javacord/src/main/java/cloud/commandframework/examples/javacord/components/DiscordApiComponent.java
  examples/example-javacord/src/main/java/cloud/commandframework/examples/javacord/components/package-info.java
  examples/example-javacord/src/main/java/cloud/commandframework/examples/javacord/modules/ExampleModule.java
  examples/example-javacord/src/main/java/cloud/commandframework/examples/javacord/modules/package-info.java
  examples/example-javacord/src/main/java/cloud/commandframework/examples/javacord/package-info.java
  examples/example-javacord/src/main/resources/logback.xml
  examples/example-jda/build.gradle.kts
  examples/example-jda/src/main/java/cloud/commandframework/examples/jda/CustomUser.java
  examples/example-jda/src/main/java/cloud/commandframework/examples/jda/ExampleBot.java
  examples/example-jda/src/main/java/cloud/commandframework/examples/jda/GuildUser.java
  examples/example-jda/src/main/java/cloud/commandframework/examples/jda/PermissionRegistry.java
  examples/example-jda/src/main/java/cloud/commandframework/examples/jda/PrivateUser.java
  examples/example-jda/src/main/java/cloud/commandframework/examples/jda/package-info.java
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 2.0.0

#650 Add specific range types
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ByteParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/DoubleParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/FloatParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/IntegerParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/LongParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/NumberParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ShortParser.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandInput.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/parsing/NumberParseException.java
  cloud-core/src/main/java/cloud/commandframework/types/range/ByteRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/DoubleRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/FloatRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/IntRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/LongRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/Range.java
  cloud-core/src/main/java/cloud/commandframework/types/range/ShortRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/package-info.java
Labels: 2.0.0

#649 feat(core): refactor numerical parsing
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ByteParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/DoubleParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/FloatParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/IntegerParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/LongParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/NumberParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/standard/ShortParser.java
  cloud-core/src/main/java/cloud/commandframework/context/CommandInput.java
  cloud-core/src/main/java/cloud/commandframework/exceptions/parsing/NumberParseException.java
  cloud-core/src/main/java/cloud/commandframework/types/range/ByteRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/DoubleRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/FloatRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/IntRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/LongRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/Range.java
  cloud-core/src/main/java/cloud/commandframework/types/range/ShortRange.java
  cloud-core/src/main/java/cloud/commandframework/types/range/package-info.java
  cloud-core/src/test/java/cloud/commandframework/ParserRegistryTest.java
Labels: 2.0.0

#647 feat: introduce `Either` as a parseable type
  cloud-annotations/src/main/java/cloud/commandframework/annotations/assembler/ArgumentAssemblerImpl.java
  cloud-annotations/src/test/java/cloud/commandframework/annotations/feature/EitherParserAnnotationsTest.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ArgumentParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/EitherParser.java
  cloud-core/src/main/java/cloud/commandframework/captions/StandardCaptionKeys.java
  cloud-core/src/main/java/cloud/commandframework/captions/StandardCaptionRegistry.java
  cloud-core/src/main/java/cloud/commandframework/types/Either.java
  cloud-core/src/main/java/cloud/commandframework/types/package-info.java
  cloud-core/src/test/java/cloud/commandframework/arguments/parser/EitherParserTest.java
Labels: 2.0.0

#652 AggregateCommandParser -> AggregateParser
  cloud-core/src/main/java/cloud/commandframework/CommandTree.java
  cloud-core/src/main/java/cloud/commandframework/arguments/StandardCommandSyntaxFormatter.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateParser.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateParserBuilder.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateParserImpl.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateParsingContext.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateParsingContextImpl.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateResultMapper.java
  cloud-core/src/main/java/cloud/commandframework/arguments/aggregate/AggregateSuggestionProvider.java
  cloud-core/src/main/java/cloud/commandframework/arguments/compound/CompoundParser.java
  cloud-core/src/test/java/cloud/commandframework/arguments/aggregate/AggregateParserTest.java
  cloud-kotlin/cloud-kotlin-extensions/src/main/kotlin/cloud/commandframework/kotlin/extension/AggregateParserBuildingExtensions.kt
Labels: 2.0.0

#651 Add mapping methods to parser descriptor
  cloud-core/src/main/java/cloud/commandframework/arguments/parser/ParserDescriptor.java
Labels: 2.0.0

#654 Add a couple helper methods to Either
  cloud-core/src/main/java/cloud/commandframework/types/Either.java
Labels: 2.0.0

#658 Move standard captions to a provider
  cloud-core/src/main/java/cloud/commandframework/CommandManager.java
  cloud-core/src/main/java/cloud/commandframework/captions/CaptionProvider.java
  cloud-core/src/main/java/cloud/commandframework/captions/CaptionRegistry.java
  cloud-core/src/main/java/cloud/commandframework/captions/CaptionRegistryImpl.java
  cloud-core/src/main/java/cloud/commandframework/captions/DelegatingCaptionProvider.java
  cloud-core/src/main/java/cloud/commandframework/captions/StandardCaptionKeys.java
  cloud-core/src/main/java/cloud/commandframework/captions/StandardCaptionsProvider.java
  cloud-core/src/main/java/cloud/commandframework/internal/ImmutableBuilder.java
  cloud-core/src/test/java/cloud/commandframework/caption/CaptionRegistryTest.java
  cloud-irc/cloud-pircbotx/src/main/java/cloud/commandframework/pircbotx/PircBotXCommandManager.java
Labels: 2.0.0

#661 Remove irc modules, moved to cloud-irc repo
  cloud-irc/cloud-pircbotx/build.gradle.kts
  cloud-irc/cloud-pircbotx/src/main/java/org/incendo/cloud/pircbotx/CloudListenerAdapter.java
  cloud-irc/cloud-pircbotx/src/main/java/org/incendo/cloud/pircbotx/PircBotXCommandManager.java
  cloud-irc/cloud-pircbotx/src/main/java/org/incendo/cloud/pircbotx/arguments/UserParser.java
  cloud-irc/cloud-pircbotx/src/main/java/org/incendo/cloud/pircbotx/arguments/package-info.java
  cloud-irc/cloud-pircbotx/src/main/java/org/incendo/cloud/pircbotx/package-info.java
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 2.0.0
